/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompetencesRouteImport } from './routes/competences'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetencesSlugRouteImport } from './routes/competences.$slug'

const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencesRoute = CompetencesRouteImport.update({
  id: '/competences',
  path: '/competences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencesSlugRoute = CompetencesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompetencesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competences': typeof CompetencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/parcours': typeof ParcoursRoute
  '/projets': typeof ProjetsRoute
  '/competences/$slug': typeof CompetencesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competences': typeof CompetencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/parcours': typeof ParcoursRoute
  '/projets': typeof ProjetsRoute
  '/competences/$slug': typeof CompetencesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competences': typeof CompetencesRouteWithChildren
  '/contact': typeof ContactRoute
  '/parcours': typeof ParcoursRoute
  '/projets': typeof ProjetsRoute
  '/competences/$slug': typeof CompetencesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competences'
    | '/contact'
    | '/parcours'
    | '/projets'
    | '/competences/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competences'
    | '/contact'
    | '/parcours'
    | '/projets'
    | '/competences/$slug'
  id:
    | '__root__'
    | '/'
    | '/competences'
    | '/contact'
    | '/parcours'
    | '/projets'
    | '/competences/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetencesRoute: typeof CompetencesRouteWithChildren
  ContactRoute: typeof ContactRoute
  ParcoursRoute: typeof ParcoursRoute
  ProjetsRoute: typeof ProjetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competences': {
      id: '/competences'
      path: '/competences'
      fullPath: '/competences'
      preLoaderRoute: typeof CompetencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competences/$slug': {
      id: '/competences/$slug'
      path: '/$slug'
      fullPath: '/competences/$slug'
      preLoaderRoute: typeof CompetencesSlugRouteImport
      parentRoute: typeof CompetencesRoute
    }
  }
}

interface CompetencesRouteChildren {
  CompetencesSlugRoute: typeof CompetencesSlugRoute
}

const CompetencesRouteChildren: CompetencesRouteChildren = {
  CompetencesSlugRoute: CompetencesSlugRoute,
}

const CompetencesRouteWithChildren = CompetencesRoute._addFileChildren(
  CompetencesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetencesRoute: CompetencesRouteWithChildren,
  ContactRoute: ContactRoute,
  ParcoursRoute: ParcoursRoute,
  ProjetsRoute: ProjetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
